name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm ci

    - name: Build and Deploy
      run: |
        npm run deploy
      env:
        DAVINCI: ${{ secrets.DAVINCI }}
